image: docker:latest

variables:
  DOCKER_REGISTRY: registry.gitlab.com
  DOCKER_IMAGE_NAME: ${CI_REGISTRY_IMAGE}/statistics-api

services:
  - docker:dind

stages:
  - build

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$CI_COMMIT_SHA -f GameAnalytics/Dockerfile GameAnalytics
    - docker push $DOCKER_IMAGE_NAME:$CI_COMMIT_SHA
    - docker tag $DOCKER_IMAGE_NAME:$CI_COMMIT_SHA $DOCKER_IMAGE_NAME:latest
    - docker push $DOCKER_IMAGE_NAME:latest
  only:
    - main
    - deployment