version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: platform-analytics-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: platform_analytics
    volumes:
      - ./platform_analytics_dump.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    image: opeyemimomodu/statistics-api:latest  # Add this line
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: platform_analytics
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy