version: '3.8'

services:

  stats-db:
    image: ${STATS_DB_IMAGE}:${CI_COMMIT_SHA}
    ports:
      - 3309:3309
    environment:
      MYSQL_DATABASE: platform_analytics
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  stats-api:
    image: ${STATS_API_IMAGE}:${CI_COMMIT_SHA}
    ports:
      - 8001:8001
    environment:
      MYSQL_DATABASE: platform_analytics
      MYSQL_HOST: stats-db

  prediction-api:
    image: ${PREDICTION_IMAGE}:${CI_COMMIT_SHA}
    ports:
      - 8002:8002

  analytics-consumer:
    image: ${ANALYTICS_CONSUMER_IMAGE}:${CI_COMMIT_SHA}
    ports:
      - 3309:3309
      - 8001:8001
      - 8002:8002
    environment:
      MYSQL_DATABASE: platform_analytics
      MYSQL_HOST: stats-db
      RABBITMQ_HOST: 48.209.190.184
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: myuser

networks:
  default:
    name: game-analytics-network