version: '3'
services:
  stats-db:
    image: ${STATS_DB_IMAGE}:${CI_COMMIT_SHA}
    ports:
      - "3309:3306"
    environment:
      - MYSQL_DATABASE=platform_analytics
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

  stats-api:
    image: ${STATS_API_IMAGE}:${CI_COMMIT_SHA}
    ports:
      - "8001:8001"
    depends_on:
      - stats-db

  prediction-api:
    image: ${PREDICTION_IMAGE}:${CI_COMMIT_SHA}
    ports:
      - "8002:8002"
    depends_on:
      - stats-db

  analytics-consumer:
    image: ${ANALYTICS_CONSUMER_IMAGE}:${CI_COMMIT_SHA}
    depends_on:
      - stats-db