version: '3.8'

services:
  platform_analytics_db:
    build: .
    image: opeyemimomodu/statistics-db:latest
    container_name: platform_analytics_mysql
    restart: always
    environment:
      MYSQL_DATABASE: platform_analytics
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - platform_analytics_data:/var/lib/mysql
#      - ./platform_analytics_backup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - platform_analytics_network

networks:
  platform_analytics_network:
    name: platform_analytics_network
    driver: bridge

volumes:
  platform_analytics_data: